// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kotlquhcezutnohcovie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvdGxxdWhjZXp1dG5vaGNvdmllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzQyNzIsImV4cCI6MjA2MDYxMDI3Mn0.A8WkCaaraiNLVqmIOJLkecptrQq46LNRdLR8-aIqlEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);